[tool.poetry]
name = "rclip"
version = "1.3.2a0"
description = "AI-Powered Command-Line Photo Search Tool"
authors = ["Yurij Mikhalevich <yurij@mikhalevi.ch>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/yurijmikhalevich/rclip"
keywords = ["image search", "computer vision", "photography"]
classifiers = [
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Science/Research",
  "Topic :: Multimedia :: Graphics",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Image Processing",
  "Topic :: Scientific/Engineering :: Image Recognition",
  "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
# ftfy and regex are deps of clip; specifying them directly because poetry stopped
# resolving deps of the { url = "..." } dependencies
clip = { url = "https://github.com/openai/CLIP/archive/a1d071733d7111c9c014f024669f959182114e33.tar.gz" }
ftfy = "^6.1.1"
pillow = ">=9.0.1"
regex = "*"
requests = "~=2.26"
torch = [
  { version = "==1.13.1", source = "pypi", markers = "sys_platform != 'linux'" },
  { version = "==1.13.1+cpu", source = "pytorch-cpu", markers = "sys_platform == 'linux'" }
]
torchvision = [
  { version = "==0.14.1", source = "pypi", markers = "sys_platform != 'linux'" },
  { version = "==0.14.1+cpu", source = "pytorch-cpu", markers = "sys_platform == 'linux'" }
]
tqdm = "^4.65.0"

[tool.poetry.group.dev.dependencies]
pycodestyle = ">=2.7,<3.0"
pytest = ">=7.2.1,<8.0"

[tool.poetry.scripts]
rclip = "rclip.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pypi"
priority = "default"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
