name: Test system rclip
description: Runs e2e tests on the rclip installed system-wide

# The action expects that the code was already checked out, with lfs: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade poetry
          poetry install
    - name: Print tested rclip version
      run: |
        which rclip
        rclip --version
    - run: make test-system-rclip
