name: Test system rclip (Windows)
description: Runs e2e tests on the rclip installed system-wide on Windows

inputs:
  python:
    description: 'Python version to use'
    required: false
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}
    - name: Print commit that we are going to run the tests from
      run: git rev-parse HEAD
      shell: powershell
    - name: Install dev dependencies required to run e2e tests
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade poetry
        poetry install --no-root --only dev
      shell: powershell
    - name: Print tested rclip version (Windows)
      run: |
        Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
        refreshenv
        which rclip
        rclip --version
      shell: powershell
    - name: Run e2e tests on the rclip installed system-wide (Windows)
      run: |
        powershell -NonInteractive - <<\EOF
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          Update-SessionEnvironment
          # Round brackets in variable names cause problems with bash
          Get-ChildItem env:* | %{
            if (!($_.Name.Contains('('))) {
              $value = $_.Value
              if ($_.Name -eq 'PATH') {
                $value = $value -replace ';',':'
              }
              Write-Output ("export " + $_.Name + "='" + $value + "'")
            }
          } | Out-File -Encoding ascii $env:TEMP\refreshenv.sh
        EOF
        source "$TEMP/refreshenv.sh"

        RCLIP_TEST_RUN_SYSTEM_RCLIP=true poetry run pytest tests/e2e
      shell: bash
